# Configuration for pytest
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

# Configuration for the ruff linter
[tool.ruff.lint]
# Rules to enable
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    #"I"     # isort
]

# Rules to ignore
ignore = [
    "E501"  # lines longer than max length
]

# Configuration for the ruff formatter
[tool.ruff.format]

# Use single quotes for strings, except triple-quoted strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
